### PR TITLE
Weekly Contest 298

### PR DESCRIPTION
**Pull request by Avik-creator**
It closes the issue #4

### CODE REVIEW

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check and review.

**Comment by nishkarsh800** [comment]
@Avik-creator Just Edit the main readme by providing link to this folder

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check it now.

**Comment by nishkarsh800** [comment]
Thanks for your kind Contribution 🥇

**Pull request merged**
