### PR TITLE
Biweekly81

### LINKED ISSUE #15: Want to Add Biweekly 81
### Title
Biweekly 81

### Description
* [Count Asterisks](https://leetcode.com/contest/biweekly-contest-81/problems/count-asterisks/)
* [Count Unreachable Pairs of Nodes in an Undirected Graph](https://leetcode.com/contest/biweekly-contest-81/problems/count-unreachable-pairs-of-nodes-in-an-undirected-graph/)
* [Maximum XOR After Operations](https://leetcode.com/contest/biweekly-contest-81/problems/maximum-xor-after-operations)
* [Number of Distinct Roll Sequences](https://leetcode.com/contest/biweekly-contest-81/problems/number-of-distinct-roll-sequences)

#### Are you contributing under any open-source program ?

HSoC 2022

### PR DESCRIPTION
**Pull request by Avik-creator**
It Closes #15

### CODE REVIEW

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check and review it.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check and review it

**Comment by nishkarsh800** [comment]
@Avik-creator Give question links inside the folder readme like this.
Screenshot (132)

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check it now.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check and review it@nishkarsh800 please check it

**Comment by nishkarsh800** [comment]
Screenshot (133)
Use braces from the next line.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check it now

**Comment by nishkarsh800** [comment]
Thanks for your kind Contribution 🥇 Try to do fewer commits from the next PR. Giving Level 3 due to Continuous Good Contribution.

**Pull request merged**
