### PR TITLE
Biweekly 82

### LINKED ISSUE #24: Biweekly 82
### Title
Want to Add Biweekly 82.

### Description
I will add questions of Biweekly 82.

[Evaluate Boolean Binary Tree](https://leetcode.com/contest/biweekly-contest-82/problems/evaluate-boolean-binary-tree)
[The Latest Time to Catch a Bus](https://leetcode.com/contest/biweekly-contest-82/problems/the-latest-time-to-catch-a-bus)
[Minimum Sum of Squared Difference](https://leetcode.com/contest/biweekly-contest-82/problems/minimum-sum-of-squared-difference)
[Subarray With Elements Greater Than Varying Threshold](https://leetcode.com/contest/biweekly-contest-82/problems/subarray-with-elements-greater-than-varying-threshold)

#### Are you contributing under any open-source program ?

HSoC 2022

### PR DESCRIPTION
**Pull request by Avik-creator**
## 🛠️ Fixes Issue

Closes #24

### CODE REVIEW

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check and review.

**Comment by nishkarsh800** [comment]
@Avik-creator Use the braces from the next line, it is not used in some programs.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check it now

**Comment by utkarsh006** [comment]
Screenshot (136)
Eliminate the space !

**Comment by nishkarsh800** [comment]
Screenshot (136)
@Avik-creator Eliminate the space !!

**Comment by Avik-creator** [comment]
@nishkarsh800 please check it now

**Comment by nishkarsh800** [comment]
Thanks for your kind Contribution 🥇

**Pull request merged**
