### PR TITLE
Biweekly Contest 79

### LINKED ISSUE #17: Add Biweekly Contest 79
### Title
Will add Biweekly Contest 79 solutions.

### Description
1. Check if Number Has Equal Digit Count and Digit Value
2. Sender With Largest Word Count
3. Maximum Total Importance of Roads
4. Booking Concert Tickets in Groups

#### Are you contributing under any open-source program ?
HSOC22
<hr/>

### PR DESCRIPTION
**Pull request by Rakesh9100**
## 🛠️ Fixes Issue

Closes #17 

## 👨‍💻 Changes proposed
Added Biweekly Contest 79 Solutions with approach.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I'm HSOC'22 Contributor

### CODE REVIEW

**Comment by nishkarsh800** [comment]
@Rakesh9100 Follow the guidelines and comment your approach.

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Follow the guidelines and comment your approach.

Done Kindly check. Added Readme file too. @nishkarsh800

**Comment by nishkarsh800** [comment]
Comment your whole approach. Connect over the discord channel.

**Comment by nishkarsh800** [comment]
@Rakesh9100 Close the pr by today midnight.

**Pull request closed without merging**
