### PR TITLE
Contest 297

### PR DESCRIPTION
**Pull request by Avik-creator**
It closes the Issue: #7

### CODE REVIEW

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check and review

**Comment by nishkarsh800** [comment]
@Avik-creator Use the braces from the next line. Also explain the approach in detail so that other must understand.

**Comment by Avik-creator** [comment]
@nishkarsh800 could you please explain which approach is difficult to understand?

**Comment by nishkarsh800** [comment]
@Avik-creator I have replied to your query on the Discord channel.

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check it now. I guess I have gave much better approach now.

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check and review it

**Comment by nishkarsh800** [comment]
@Avik-creator Use braces from the next line in the code.

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check it.

**Comment by nishkarsh800** [comment]
@Avik-creator Approach for ques 2 and 4 not explained.

**Comment by Avik-creator** [comment]
@nishkarsh800 there is approach written

**Comment by nishkarsh800** [comment]
@Avik-creator Resolve merge conflict.

**Pull request closed without merging**
