### PR TITLE
Contest 297

### LINKED ISSUE #7: Want to add Leetcode weekly 297
**Problem list:**

* Calculate Amount Paid in Taxes	
* Minimum Path Cost in a Grid	
* Fair Distribution of Cookies	
* Naming a Company

### PR DESCRIPTION
**Pull request by Avik-creator**
## 🛠️ Fixes Issue

Closes #7

### CODE REVIEW

**Comment by Avik-creator** [comment]
@nishkarsh800 Please Check Now

**Comment by Avik-creator** [comment]
@nishkarsh800 please check it

**Comment by Avik-creator** [comment]
@nishkarsh800 Please check it.

**Comment by nishkarsh800** [comment]
@Avik-creator Code should be in C++. You have copied the java code of ques 3 and saved it as .cpp extension.

**Comment by Avik-creator** [comment]
@nishkarsh800 I hope I have solved all the conflicts.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check

**Comment by Avik-creator** [comment]
@nishkarsh800 please check

**Comment by nishkarsh800** [comment]
Thanks for your kind Contribution 🥇 Level 2 due to too many commits.

**Comment by Avik-creator** [comment]
@nishkarsh800 no worries regarding that

**Pull request merged**
