### PR TITLE
Biweekly Contest 82

### LINKED ISSUE #13: Biweekly Contest 82
### Title
Biweekly Contest 82

### Description
Problem Statements are,
- [Evaluate Boolean Binary Tree](https://leetcode.com/contest/biweekly-contest-82/problems/evaluate-boolean-binary-tree)
- [The Latest Time to Catch a Bus](https://leetcode.com/contest/biweekly-contest-82/problems/the-latest-time-to-catch-a-bus)
- [Minimum Sum of Squared Difference](https://leetcode.com/contest/biweekly-contest-82/problems/minimum-sum-of-squared-difference)
- [Subarray With Elements Greater Than Varying Threshold](https://leetcode.com/contest/biweekly-contest-82/problems/subarray-with-elements-greater-than-varying-threshold)

#### Are you contributing under any open-source program ?
HSOC 2022

Please assign me this issue.
@nishkarsh800

### PR DESCRIPTION
**Pull request by abhisheks008**
## 🛠️ Fixes Issue #13 
🔴 Biweekly Contest 82
Added all the solutions of the 4 problems.

Closes #13 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I'm HSOC'22 Contributor

### CODE REVIEW

**Comment by nishkarsh800** [comment]
@abhisheks008 Use the braces from the next line. Also explain the approach in detail so that other must understand.

**Comment by abhisheks008** [comment]
Please review it sir @nishkarsh800

**Comment by nishkarsh800** [comment]
@abhisheks008 Read the guidelines properly and make changes. Write the file name properly. 
Ex : Longest_common_subsequence

**Comment by abhisheks008** [comment]
Sir @nishkarsh800, in the Contributing Guidelines, the naming pattern is not mentioned properly. So I think you need to read the guidelines before me. Correct me if I am wrong. 😸

**Comment by abhisheks008** [comment]
I am done with the changes sir, can you please update the Contributing Guidelines with the naming pattern of the files. That'll be great for others!

Please review my changes sir @nishkarsh800

**Comment by nishkarsh800** [comment]
@abhisheks008 Use braces from the next line in your code. Still you haven't done satisfactory changes.

**Comment by abhisheks008** [comment]
@nishkarsh800 may be this time this is okay! Sir!

**Comment by nishkarsh800** [comment]
@abhisheks008 Hope you know what's the essence of open source. Write the code which is understandable to the person who is referring to it for the first time.

function<int (TreeNode*)> dfs = [&](TreeNode *node)

**Pull request closed without merging**
